Authentication and NLPSearchService TestClass
datakaveri/iudx-catalogue-server pull request #152
Opened 2022-08-17 05:13 UTC by tanvi029

2022-08-18 09:18 UTC, kailash commented
ok to test

2022-08-19 05:35 UTC, kailash commented
retest this please

2022-08-19 06:14 UTC, tanvi029 commented
[catalog-server-coverage.pdf](https://github.com/datakaveri/iudx-catalogue-server/files/9379598/catalog-server-coverage.pdf)

2022-08-24 03:52 UTC, kailash commented
retest this please

2022-08-24 11:45 UTC, kailash requested changes
- Use assertions(`assertEquals` & `assertThrows`) to check the return values in test cases.
- In case of mocks use `verify()` to verify the interactions with mocks.

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/ExceptionHandlerTest.java
> +
use assertions, `assertThrows()` in this case

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/ExceptionHandlerTest.java
> +        exceptionHandler.handleDecodeException(routingContext);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/ExceptionHandlerTest.java
> +        exceptionHandler.handleDecodeException(routingContext);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/ExceptionHandlerTest.java
> +        exceptionHandler.handleDecodeException(routingContext);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/ExceptionHandlerTest.java
> +        exceptionHandler.handleClassCastException(routingContext);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/QueryMapperTest.java
> +        queryMapper.map2Json(queryParameters);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/QueryMapperTest.java
> +        vertxTestContext.completeNow();
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/QueryMapperTest.java
> +        vertxTestContext.completeNow();
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/QueryMapperTest.java
> +        vertxTestContext.completeNow();
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/QueryMapperTest.java
> +        vertxTestContext.completeNow();
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/RespBuilderTest.java
> +        respBuilder.withDetail(detail);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/RespBuilderTest.java
> +        respBuilder.withResult(id,method,status);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/RespBuilderTest.java
> +        respBuilder.withResult(id,method,status,detail);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/apiserver/util/RespBuilderTest.java
> +        respBuilder.getJsonResponse();
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/auditing/util/QueryBuilderTest.java
> +        vertxTestContext.completeNow();
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/auditing/util/QueryBuilderTest.java
> +        queryBuilder.buildReadQuery(request);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/authenticator/AuthenticationServiceImplTest.java
> +        authenticationService.tokenInterospect(request,authenticationInfo,handler);
use assertions and use `verify()` to test exact interactions with mocks.

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/authenticator/AuthenticationServiceImplTest.java
> +        authenticationService.tokenInterospect(request,authenticationInfo,handler);
use assertions and use verify() to test exact interactions with mocks.

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/authenticator/AuthenticationServiceImplTest.java
> +        authenticationService.isPermittedMethod(methods,operation);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/authenticator/AuthenticationServiceImplTest.java
> +        authenticationService.isPermittedMethod(methods,operation);
use assertions

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/authenticator/AuthenticationServiceImplTest.java
> +        authenticationService.tokenInterospect(request,authenticationInfo,handler);
use assertions and use verify() to test exact interactions with mocks.

2022-08-24 11:45 UTC, kailash commented on src/test/java/iudx/catalogue/server/authenticator/AuthenticationServiceImplTest.java
> +        authenticationService.tokenInterospect(request,authenticationInfo,handler);
use assertions

2022-08-29 07:53 UTC, merged