mlayer-dataset-API
datakaveri/iudx-catalogue-server pull request #206
Opened 2023-02-14 09:09 UTC by tanvi029

2023-02-20 09:52 UTC, pranavrd commented on src/main/java/iudx/catalogue/server/database/Constants.java
> +      "{\"query\":{\"bool\":{\"must\":{\"match\":{\"type.keyword\":\"iudx:Resource\"}}}},\"_source\":{\"includes\": [\"id\",\"resourceGroup\"]},\"size\":980}";
remove size field

2023-02-20 10:09 UTC, pranavrd commented on src/main/java/iudx/catalogue/server/database/ElasticClient.java
> +                          .put("schema",schema);
Use string constants wherever possible

2023-02-20 10:10 UTC, pranavrd commented
ok to test

2023-02-21 04:02 UTC, kailash requested changes

2023-02-22 06:42 UTC, pranavrd commented
LGTM

2023-02-22 07:11 UTC, kailash approved these changes
LGTM

2023-02-22 07:22 UTC, merged