pmd-changes
datakaveri/iudx-catalogue-server pull request #225
Opened 2023-04-20 04:51 UTC by tanvi029

2023-04-20 06:21 UTC, pranavrd commented
ok to test

2023-04-24 08:01 UTC, pranavrd commented on google_checks.xml
> +        <property name="file" value="$AsyncServiceVertxEBProxy.java$"/>
Same as above

2023-04-24 08:11 UTC, pranavrd requested changes
Resolve above comments

2023-04-24 09:06 UTC, pranavrd approved these changes
LGTM

2023-04-25 03:52 UTC, kailash requested changes

2023-04-25 03:52 UTC, kailash commented on src/main/java/iudx/catalogue/server/apiserver/MlayerApis.java
remove commented code

2023-04-26 12:08 UTC, kailash approved these changes

2023-04-27 04:37 UTC, merged