quality gate in jenkinsCI
datakaveri/iudx-catalogue-server pull request #229
Opened 2023-05-03 15:15 UTC by ananjaykumar2

* since there is still 7-8 warnings in pmd and checkstyle that's why **threshold** is **10**.

2023-05-03 16:14 UTC, pranavrd commented
Ok to test

2023-05-04 05:02 UTC, kailash requested changes

2023-05-04 05:02 UTC, kailash commented on Jenkinsfile
> +                               qualityGates: [[threshold:10, type: 'TOTAL', unstable: false]],
```suggestion
                               qualityGates: [[threshold:8, type: 'TOTAL', unstable: false]],
```
only 7 warnings are there for checkstyle in catalogue server

2023-05-04 05:02 UTC, kailash commented on Jenkinsfile
> +                               qualityGates: [[threshold:10, type: 'TOTAL', unstable: false]],
```suggestion
                               qualityGates: [[threshold:9, type: 'TOTAL', unstable: false]],
```

2023-05-04 05:38 UTC, kailash approved these changes

2023-05-04 06:26 UTC, merged