Feat/cos item
datakaveri/iudx-catalogue-server pull request #254
Opened 2023-08-14 07:33 UTC by pranavrd

2023-08-16 05:29 UTC, kailash requested changes
As a suggestion, you can also try to move delegate, provider, and cos_admin authorization logic[only approved delegates can work on their items, or providers can update only their items] inside their respective classes DelegateAuthStrategy, ProviderAuthStrategy etc..

2023-08-16 05:29 UTC, kailash commented on src/main/java/iudx/catalogue/server/authenticator/JwtAuthenticationServiceImpl.java
> +    return null;
Use Promise and Future, avoid returning null from methods

2023-08-16 05:29 UTC, kailash commented on src/main/java/iudx/catalogue/server/authenticator/KcAuthenticationServiceImpl.java
> +  private Future<Boolean> isValidAdmin(JwtData jwtData) {
The duplicate method. `isValidAdmin` method is also there in `JwtAuthServiceImpl`, try to use the same method and avoid code duplication.

2023-08-28 04:17 UTC, pranavrd commented
retest this please

2023-08-28 05:47 UTC, pranavrd commented
retest this please

2023-08-28 09:14 UTC, kailash approved these changes

2023-08-28 09:27 UTC, merged