Instance changes
datakaveri/iudx-catalogue-server pull request #255
Opened 2023-08-16 05:08 UTC by tanvi029

2023-08-16 05:19 UTC, kailash requested changes
Use Future instead of callback handlers in service proxy definitions,

2023-08-16 05:19 UTC, kailash commented on src/main/java/iudx/catalogue/server/authenticator/KcAuthenticationServiceImpl.java
> +            || endpoint.equals("/internal/ui/instance")) {
Use an enum or constants file for String constants

2023-08-16 05:31 UTC, kailash commented
ok to test

2023-08-16 09:42 UTC, pranavrd commented on src/main/java/iudx/catalogue/server/database/DatabaseServiceImpl.java
> +    if (id.isBlank()) {
check for id == null before isBlank()

2023-08-18 09:44 UTC, pranavrd approved these changes
LGTM

2023-08-21 05:43 UTC, kailash approved these changes

2023-08-21 06:04 UTC, merged