Added Pagination
datakaveri/iudx-catalogue-server pull request #318
Opened 2024-03-05 07:24 UTC by Gaurav-git06

2024-03-05 09:36 UTC, ankitmashu requested changes
1.  Check PMD and Checkstyle
2.  Docs not updated

2024-03-05 09:59 UTC, ananjaykumar2 requested changes

2024-03-05 09:59 UTC, ananjaykumar2 commented on src/main/java/iudx/catalogue/server/apiserver/MlayerApis.java
> +//                  if (handler.succeeded()) {
i guess unnecessary comments/lines should be removed.

2024-03-05 09:59 UTC, ananjaykumar2 commented on src/main/java/iudx/catalogue/server/apiserver/MlayerApis.java
> +        String offset = routingContext.request().getParam("offset");
it will be good to use constants instead of String.

2024-03-07 10:23 UTC, ankitmashu commented on docs/openapi.yaml
> +        - name: limit
Docs is not properly updated, you have to mention in introduction or in some other header that this bla bla api pagination introduced with maximum value and by default value to be allowed. Check other server docs

2024-03-12 11:47 UTC, pranavrd commented on docs/openapi.yaml
> +       - <b>/internal/ui/domain</b>
Include `/search` API in this list

2024-03-12 11:49 UTC, pranavrd approved these changes

2024-03-13 08:54 UTC, pranavrd commented
ok to test

2024-03-14 06:25 UTC, pranavrd commented
retest this please

2024-03-14 06:50 UTC, merged